# http://projecteuler.net/index.php?section=problems&id=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

def fib_iter
  raise ArgumentError unless block_given?
  a, b = 0, 1
  loop do
    yield a
    a, b = b, a + b
  end
end

puts enum_for(:fib_iter).take_while {|e| e < 4_000_000 }.select {|e| e % 2 == 0 }.inject {|sum, e| sum += e } 
