# http://projecteuler.net/index.php?section=problems&id=45
# 
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle      T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
# Pentagonal      P_(n)=n(3n−1)/2       1, 5, 12, 22, 35, ...
# Hexagonal       H_(n)=n(2n−1)       1, 6, 15, 28, 45, ...
# 
# It can be verified that T_(285) = P_(165) = H_(143) = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

def T(n)
  return n * (n + 1) / 2
end

def P(n)
  return n * (3 * n - 1) / 2
end

def is_P?(n)
  return n == P((1 + Math.sqrt(1 + 24 * n).to_i) / 6)
end

def H(n)
  return n * (2 * n - 1)
end

def is_H?(n)
  return n == H((1 + Math.sqrt(1 + 8 * n).to_i) / 4)
end

286.upto(1.0/0.0) do |n|
  t = T(n)
  if is_P?(t) && is_H?(t)
    puts t
    break
  end
end
